### ISSUE TITLE
user-repositories break assumptions at multiple places

### ISSUE THREAD

**Issue by soumith** [amzn/oss-dashboard#115]
if one is tracking user-repositories (i.e. not under an org), for example: `ry/v8worker`, then many parts of the code break.

The code eventually goes into an infinite loop of API accesses like this:
`ry GitHub client error, pushing command back on queue: GET https://api.github.com/orgs/ry/repos?per_page=100: 404 - Not Found // See: https://developer.github.com/v3/repos/#list-organization-repositories`

**Comment by hyandell** [comment]
It currently only supports org/repos, org and user (ie: no user-repos). 

https://github.com/amzn/oss-dashboard/blob/master/dashboard-context.rb needs to be improved so that repositories() is able to include user repos. Hopefully fixing just that would cascade along.

**Comment by hyandell** [comment]
I think there are two ways to solve it.

A) Change the code so that it's able to tell if 'xyzzy' is a login or an organization.
B) Add a login-repositories: configuration option.

The problem with A is that it requires a call to GitHub, and that I don't think there is an ideal query so it's relying on a side-effect (for example trying to get organization repositories and seeing it error). 

So I'm leaning to B).

**Comment by jamesiri** [comment]
#142
